config/routes.rb
Rails.application.routes.draw do
  get 'service/shirts'
  get 'service/dry_cleaning'
  get 'service/household_linen'
  get 'service/repairs_alterations'
  get 'service/wedding_dress_cleaning'
  get 'service/leather_suede'
  get 'service/laundry_service'
  get 'service/collection_delivery'
  root to: 'home#index'
  get "/pricing" => 'home#pricing'
  resources :home do
    collection do
      post :place_order
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
  end

  def pricing
  end

  def place_order
    if params[:name].nil?
      flash[:danger] = 'Name cannot be blank'
    elsif  params[:email].nil?
      flash[:danger] = 'Email cannot be blank'
    elsif params[:phone].nil?
      flash[:danger] = 'Phone number cannot be blank'
    elsif params[:pick_up].nil? || params[:pick_up].empty?
      flash[:danger] = 'Pick time cannot be blank'
    elsif params[:delivery].nil? || params[:pick_up].empty?
      flash[:danger] = 'Delivery time cannot be blank'
    elsif params[:address].nil?
      flash[:danger] = 'Delivery time cannot be blank'
    elsif params[:dry_cleaning].nil? && params[:shirt_service].nil? && params[:bedlinen_and_household].nil? && params[:repair_and_alterations].nil? && params[:dress_cleaning].nil? && params[:leather_and_suede_cleaning].nil?
      flash[:danger] = 'Please select one service for an order'
    else
      OrderMailer.send_email_to_owner(params).deliver_now
      flash[:success] = 'Order placed successfully.'
    end
    redirect_to home_index_path
  end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController

  def shirts
  end

  def dry_cleaning
  end

  def household_linen
  end

  def repairs_alterations
  end

  def wedding_dress_cleaning
  end

  def leather_suede
  end

  def laundry_service
  end

  def collection_delivery
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def custom
  end
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/home/index.html.erb
<!-- banner -->
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>" style="text-align: center !important"><%= value %></div>
<% end %>
  <%= render "layouts/partials/home_banner" %>
<!-- //banner -->
<!-- about -->
<section class="about-w3ls" id="about">
  <div class="container">
    <div class="jumbotron text-center pt-0">
      <img src="/assets/logo.jpeg" alt="" class="img-fluid rounded-circle store-front">
      <h1 class="ab-title my-5">We Promise Highest Quality Care</h1>
      <h2 class="lead">To become the leading dry cleaning and laundry services with focus on high quality, unrivalled customer service and environmentally friendly operations whilst nurturing the needs of our customers.</h2>
      <hr class="my-4">
      <p>No job is too large or small.<br/>
      We do just about any type of dry cleaning and laundry services under the sun for all your garments.</p>
      <p class="lead">
        <a class="btn btn-primary btn-lg mt-3 scroll" href="#services" role="button">Learn more</a>
      </p>
    </div>
  </div>
</section>
<!-- //about -->
<!--services-->
<!-- <div class="agileits-services py-md-5 py-3">
  <div class="container">
    <h3 class="w3ls-title text-center text-capitalize">what we do</h3>
    <div class="agileits-services-row row py-md-5 pb-5">
      <div class="col-lg-12 col-md-6 agileits-services-grids mt-lg-0 mt-3">
        <span class="fab fa-schlix p-4"></span>
        <h4 class="mt-2 mb-3">Faster Service</h4>
        <p>We are know to our fast services. Feel Free to contact for dry clean service at any time.</p>
      </div>
    </div>
  </div>
</div> -->
<!-- //services-->
<!--why choose us-->
<div class="agileits-services py-md-5 py-3" id="services">
  <div class="container">
    <h3 class="w3ls-title text-center text-capitalize">why choose us</h3>
    <p style="text-align: center">We have been providing professional dry cleaning and laundry services in Archway to individuals and corporate customers for over 20 years. Our success and growth is due to our commitment to provide the best professional dry cleaning and laundry at very competitive prices and impeccable service.</p>
    <div class="agileits-services-row row">
      <div class="col-lg-3 col-md-6 agileits-services-grids">
        <span class="fas fa-credit-card p-4"></span>
        <h4 class="mt-2 mb-3">Affordable Prices</h4>
        <p>Enjoy the most affordable prices on the market.</p>
      </div>
      <div class="col-lg-3 col-md-6 agileits-services-grids">
        <span class="fas fa-hand-point-right p-4"></span>
        <h4 class="mt-2 mb-3">Easy to Use</h4>
        <p>Getting the laundry done has never been easier.</p>
      </div>

      <div class="col-lg-3 col-md-6 agileits-services-grids">
        <span class="fa fa-truck p-4"></span>
        <h4 class="mt-2 mb-3">Free Collection & Delivery</h4>
        <p>We’ll pick up your clothes and drop them off again, FREE of charge.</p>
      </div>
      <div class="col-lg-3 col-md-6 agileits-services-grids">
        <span class="fas fa-star p-4"></span>
        <h4 class="mt-2 mb-3">Quality Cleaning</h4>
        <p>We carefully clean, fold, and package your clothes ready to be returned to you.</p>
      </div>
    </div>
  </div>
</div>


<!-- <div class="agileits-services py-md-5 py-3">
  <div class="container">
    <h3 class="w3ls-title text-center text-capitalize">Why Choose Us</h3>
    <div class="agileits-services-row row py-md-5 pb-5">
      <div class="col-lg-12 col-md-6 agileits-services-grids mt-lg-0 mt-3">
        <span class="fas fa-users p-4"></span>
        <h4 class="mt-2 mb-3">Professional Service</h4>
        <p style="font-family: 'Raleway', sans-serif;">We have been providing professional dry cleaning and laundry services in Archway to individuals and corporate customers for over 20 years. Our success and growth is due to our commitment to provide the best professional dry cleaning and laundry at very competitive prices and impeccable service.</p>
      </div>
    </div>
  </div>
</div> -->
<!-- //why choose us-->
<!---728x90--->
<!-- stats -->
<!-- <section class="agile_stats text-center py-5">
  <div class="container pt-sm-5">
    <div class="stats_agile mb-sm-5 mb-3">
      <h3 class="stat-title text-capitalize pb-md-5 pb-4">let us do your dry clean</h3>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="counter pt-5 px-3 pb-3">
          <i class="far fa-smile fa-2x"></i>
          <div class="timer count-title count-number mt-2" data-to="5100" data-speed="1500"></div>
          <p class="count-text text-capitalize">happy customers</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 mt-md-0 mt-sm-5 mt-3">
        <div class="counter  pt-5 px-3 pb-3">
          <i class=" fab fa-stack-overflow fa-2x"></i>
          <div class="timer count-title count-number mt-2" data-to="4783" data-speed="1500"></div>
          <p class="count-text text-capitalize">dry clean</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 mt-lg-0 mt-sm-5 mt-3">
        <div class="counter  pt-5 px-3 pb-3">
          <i class="fas fa-eraser fa-2x"></i>
          <div class="timer count-title count-number mt-2" data-to="2184" data-speed="1500"></div>
          <p class="count-text text-capitalize">ironing</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6  mt-lg-0 mt-sm-5 mt-3">
        <div class="counter  pt-5 px-3 pb-3">
          <i class="fas fa-exclamation fa-2x"></i>
          <div class="timer count-title count-number mt-2" data-to="1084" data-speed="1084"></div>
          <p class="count-text text-capitalize">stain removal</p>
        </div>
      </div>
    </div>
  </div>
</section> -->
<!-- //stats -->
<!-- team -->
<!-- <section class="wthree-row py-5" id="team">
  <div class="container py-md-5 py-3">
    <div class="py-md-5 py-3 bg-pricemain text-center">
      <h3 class="w3ls-title text-center text-capitalize pb-md-5 pb-4">meet our team</h3>
    </div>
    <div class="row">
      <div class="col-lg-3 col-sm-6 team-grids">
        <div class="team-effect">
          <img src="/assets/t1.jpg" alt="img" class="img-responsive">
        </div>
        
        <div class="footerv2-w3ls mt-3">
          <h4>John Smith</h4>
          <p>Creative Director</p>
          <ul class="social-iconsv2 agileinfo">
            <li>
              <a href="#">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fab fa-google-plus-g"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div>
        
      </div>
      <div class="col-lg-3 col-sm-6 team-grids mt-sm-0 mt-5">
        <div class="team-effect">
          <img src="/assets/t3.jpg" alt="img" class="img-responsive">
        </div>
        
        <div class="footerv2-w3ls mt-3">
          <h4>Thomson Doe</h4>
          <p>Chairman</p>
          <ul class="social-iconsv2 agileinfo">
            <li>
              <a href="#">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fab fa-google-plus-g"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div>
       
      </div>
      <div class="col-lg-3 col-sm-6 team-grids mt-lg-0 mt-5">
        <div class="team-effect">
          <img src="/assets/t2.jpg" alt="img" class="img-responsive">
        </div>
        
        <div class="footerv2-w3ls mt-3">
          <h4>Smith Kevin</h4>
          <p>Executive Manager</p>
          <ul class="social-iconsv2 agileinfo">
            <li>
              <a href="#">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fab fa-google-plus-g"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div>
        
      </div>
      <div class="col-lg-3 col-sm-6 team-grids mt-lg-0 mt-5">
        <div class="team-effect">
          <img src="/assets/t4.jpg" alt="img" class="img-responsive">
        </div>
        
        <div class="footerv2-w3ls mt-3">
          <h4>Laura Hill</h4>
          <p>HR Manager</p>
          <ul class="social-iconsv2 agileinfo">
            <li>
              <a href="#">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fab fa-google-plus-g"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div>
        
      </div>
    </div>
  </div>
</section> -->
<!-- //team -->
<!-- gallery -->
<!-- <div class="gallery  py-md-5 py-3" id="gallery">
  <div class="container">
    <h3 class="w3ls-title text-center text-capitalize py-md-4 py-3">gallery</h3>
    <div class="gallery_gds row pt-md-5 pt-3">
      <div class="col-4  gal-w3l">
        <div class="agileits-img">
          <a href="/assets/cg2.jpeg" class="swipebox" title="Ironing">
            <img src="/assets/cg2.jpg" alt="" class="img-responsive img-style row2" />
          </a>
        </div>
      </div>
      <div class="col-4  gal-w3l">
        <div class="agileits-img">
          <a href="/assets/cg4.jpg" class="swipebox" title="Stock">
            <img src="/assets/cg4.jpg" alt="" class="img-responsive img-style row2" />
          </a>
        </div>
      </div>
      <div class="col-4  gal-w3l">
        <div class="agileits-img">
          <a href="/assets/g7.jpg" class="swipebox" title="Ready for pickup">
            <img src="/assets/g7.jpg" alt="" class="img-responsive img-style row2" />
          </a>
        </div>
      </div>
    </div>
    <div class="gallery_gds row">
      <div class="col-4  gal-w3l">
        <div class="agileits-img">
          <a href="/assets/cg8.jpg" class="swipebox" title="Front Desk">
            <img src="/assets/cg8.jpg" alt="" class="img-responsive img-style row2" />
          </a>
        </div>
      </div>
      <div class="col-4  gal-w3l">
        <div class="agileits-img">
          <a href="/assets/g9.jpg" class="swipebox" title="Techniques">
            <img src="/assets/g9.jpg" alt="" class="img-responsive img-style row2" />
          </a>
        </div>
      </div>
    </div>
  </div>
</div> -->
<!-- testimonials -->
<!-- <section class="wthree-row py-5 testi-agile" id="testimonials">
  <div class="container py-md-5 py-3">
    <h3 class="w3ls-title text-center text-capitalize pb-md-5 pb-4">testimonials</h3>
    <div class="w3_testimonials_grids w3_testimonials_grids">
      <div class="sreen-gallery-cursual">
        <div id="owl-demo" class="owl-carouselpb-5">
          <div class="item-owl text-center">
            <div class="img-agile">
              <i class="fas fa-user"></i>
              <h6 class="mt-3 text-white">Michael Paul</h6>
            </div>
            <div class="test-review test-tooltip1">
              <p class="mx-auto mt-3 text-white">
                <i class="fa fa-quote-left" aria-hidden="true"></i> Thank you for everything, it is always a pleasure to hear from you and I have to say,your business is by far the most well organized, well curated, well stocked, descriptive and fairly priced that I’ve ever seen.
                <i class="fa fa-quote-right" aria-hidden="true"></i>
              </p>
            </div>
          </div>
          <div class="item-owl">
            <div class="img-agile">
              <i class="fas fa-user"></i>
              <h6 class="mt-3 text-white">Riya Allen</h6>
            </div>
            <div class="test-review test-tooltip1">
              <p class="mx-auto mt-3 text-white">
                <i class="fa fa-quote-left" aria-hidden="true"></i> A truly enjoyable dry cleaning experience. Thank you. Warm regards, RA".
                <i class="fa fa-quote-right" aria-hidden="true"></i>
              </p>
            </div>
          </div>
          <div class="item-owl">
            <div class="img-agile">
              <i class="fas fa-user"></i>
              <h6 class="mt-3 text-white">Elizabeth Keen</h6>
            </div>
            <div class="test-review test-tooltip1">
              <p class="mx-auto mt-3 text-white">
                <i class="fa fa-quote-left" aria-hidden="true"></i> My overall online laundry experience with Quick Silvers has been very positive so far. I would highly recommend your business to anyone I know.
                <i class="fa fa-quote-right" aria-hidden="true"></i>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> -->
<!-- //testimonials -->
<!---728x90--->
<!-- contact -->

<!-- //contact -->

<!-- order modal -->

app/views/layouts/partials/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
      <%= link_to('<img src="/assets/logo.jpeg" class="header-logo">'.html_safe, root_path, class: "navbar-brand", method: "get") %>
      <%# <a class="navbar-brand" href="index.html">
        <i class="fab fa-empire"></i>
      </a> %>
      <button type="button" class="btn btn-info btn-lg-block w3ls-btn px-4 text-uppercase font-weight-bold" data-toggle="modal"
            aria-pressed="false" data-target="#exampleModal" id="order-btn-outside">
          book now
      </button>
      <button class="navbar-toggler ml-md-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
          aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto text-center">
          <li class="nav-item active">
            <%= link_to('Home<span class="sr-only">(current)</span>'.html_safe, root_path, class: "nav-link", method: "get") %>
          </li>
          <li class="nav-item">
            <!-- <a class="nav-link scroll" href="#contact">Pricing Plans</a> -->
            <%= link_to("Pricing Plans", pricing_path, class: "nav-link", id: "pricing-nav-link") %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle services-nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
              Services
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <span class="dropdown-item scroll">
                  <%= link_to('Dry Cleaning'.html_safe, service_dry_cleaning_path, class: "nav-link", method: "get") %>
              </span>
              <span class="dropdown-item scroll">
              <%= link_to('Shirts Service'.html_safe, service_shirts_path, class: "nav-link", method: "get") %>
              </span>
              
              <span class="dropdown-item scroll">
                <%= link_to('Bed linen & Household'.html_safe, service_household_linen_path, class: "nav-link", method: "get") %>
              </span>
              <span class="dropdown-item scroll">
              <%= link_to('Repairs & Alterations'.html_safe, service_repairs_alterations_path, class: "nav-link", method: "get") %>
              </span>
              <span class="dropdown-item scroll">
                <%= link_to('Wedding Dress Cleaning'.html_safe, service_wedding_dress_cleaning_path, class: "nav-link", method: "get") %>
              </span>
              <span class="dropdown-item scroll">
                <%= link_to('Leather & Suede Cleaning'.html_safe, service_leather_suede_path, class: "nav-link", method: "get") %>
              </span>
              <span class="dropdown-item scroll">
                <%= link_to('Collection and Delivery'.html_safe, service_collection_delivery_path, class: "nav-link", method: "get") %>
              </span>
              <!-- <a class="dropdown-item scroll" href="#services">Services</a> -->
              <!-- <a class="dropdown-item scroll" href="#team">Team</a> -->
              <!-- <a class="dropdown-item scroll" href="#gallery">Gallery</a> -->
              <!-- <div class="dropdown-divider"></div> -->
              <!-- <a class="dropdown-item scroll" href="#testimonials">Testimonials</a> -->
            </div>
          </li>
          <% if controller_name == "home" and action_name != "pricing" %>
            <li class="nav-item">
              <a class="nav-link scroll" href="#about">about</a>
            </li>
          <% end %>
          <li class="nav-item">
            <a class="nav-link scroll" href="#contact">contact</a>
          </li>
        </ul>
        <button type="button" class="btn btn-info btn-lg-block w3ls-btn px-4 text-uppercase font-weight-bold" data-toggle="modal"
            aria-pressed="false" data-target="#exampleModal" id="order-btn-inside">
          book now
        </button>
      </div>
    </nav>
  </div>
</header>
<marquee scrollamount="10">
  <span class="marquee-text">
    We are open Monday to Friday 8:00 am to 7:00 pm, Saturday 8:00 am to 6:00 pm, Sunday 10:00 am to 4:00 pm, Pickup & Deliveries are available Monday to Saturday 8:00 am to 7:00 pm Min order £20 T&C Apply
  </span>  
</marquee>
<script type="text/javascript">
  if(<%= action_name == "pricing" %>){
    $(".navbar-nav .active").removeClass("active")
    $(".navbar-nav #pricing-nav-link").addClass("active")
  }else if(<%= controller_name == "service" %>){
    $(".navbar-nav .active").removeClass("active")
    $(".navbar-nav .services-nav-link").addClass("active")
  }
</script>

app/views/layouts/partials/_order_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-capitalize" id="exampleModalLabel1">Book your Order</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag(place_order_home_index_path, method: :post, :html => {:class => 'p-3'}) do %>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Your Name</label>
            <%= text_field_tag :name, "",  type: "text", class: "form-control", placeholder:"", id: "recipient-name", required: "" %>   
          </div>

          <div class="form-group">
            <label for="recipient-name1" class="col-form-label">Your Email</label>
            <%= text_field_tag :email, "",  type: "email", class: "form-control", placeholder:"", id: "recipient-name1", required: "" %> 
          </div>

          <div class="form-group">
            <label for="recipient-name2" class="col-form-label">Phone</label>
            <%= text_field_tag :phone, "", type: "tel", pattern: '\d{11}', class: "form-control", placeholder:"", id: "recipient-name2", required: "", title: 'Phone Number (Format: +02072811111)' %> 
          </div>

          <div class="form-group">
            <label class="mr-2 col-form-label">Pick Up</label>
            <%= text_field_tag :pick_up, nil, type: "text", placeholder: "YYYY/MM/DD HH:MM", class: "form-control", required: "", id: "datepicker1", autocomplete: 'off'%> 
          </div>

           <div class="form-group">
            <label class="mr-2 col-form-label">Delivery</label>
            <%= text_field_tag :delivery, nil, type: "text", placeholder: "YYYY/MM/DD HH:MM", class: "form-control", required: true, id: "datepicker2", autocomplete: 'off'%> 
          </div>

           <div class="form-group">
            <label for="comment" class="col-form-label">Special Instruction (Optional):</label>
            <%= text_area_tag :special_instructions, nil,  class: "form-control", rows: "3", id: "comment" %>
          </div>

          <div class="form-check">
            <label class="form-check-label col-form-label" for="l1">
              <%= check_box_tag :dry_cleaning, 1, false, class: "form-check-input" %> Dry Cleaning
            </label>
          </div>

          <div class="form-check">
            <label class="form-check-label col-form-label" for="l2">
              <%= check_box_tag :shirt_service, 1, false, class: "form-check-input" %> Shirt Service
            </label>
          </div>

          <div class="form-check">
            <label class="form-check-label col-form-label" for="l3">
              <%= check_box_tag :bedlinen_and_household, 1, false, class: "form-check-input" %>  Bedlinen & Household
            </label>
          </div>

          <div class="form-check">
            <label class="form-check-label col-form-label" for="l4">
              <%= check_box_tag :repair_and_alterations, 1, false, class: "form-check-input" %>Repair & Alterations
            </label>
          </div>

          <div class="form-check">
            <label class="form-check-label col-form-label" for="l5">
              <%= check_box_tag :dress_cleaning, 1, false, class: "form-check-input" %>Dresses Cleaning
            </label>
          </div>

          <div class="form-check">
            <label class="form-check-label col-form-label" for="l6">
              <%= check_box_tag :leather_and_suede_cleaning, 1, false, class: "form-check-input" %>Leather & Suede Cleaning
            </label>
          </div>

           <div class="form-group">
            <label for="comment" class="col-form-label">Pickup Address:</label>
            <%= text_area_tag :address, nil,  class: "form-control", rows: "5", id: "comment", :required => true %>
          </div>

          <div class="right-w3l">
            <%= submit_tag "Place Order", class: "form-control" %> 
          </div>   
        <% end %>  
      </div>
    </div>
  </div>
</div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.css" integrity="sha512-bYPO5jmStZ9WI2602V2zaivdAnbAhtfzmxnEGh9RwtlI00I9s8ulGe4oBa5XxiC6tCITJH/QG70jswBhbLkxPw==" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha512-AIOTidJAcHBH2G/oZv9viEGXRqDNmfdPVPYOYKGy3fti0xIplnlgMHUGfuNRzC6FkzIo0iIxgFnr9RikFxK+sw==" crossorigin="anonymous"></script>

<script>
  $(function() {
      $("#datepicker1").datetimepicker({
        minDateTime: new Date(),
        defaultDate: false,
        autoclose: true
      });

      $("#datepicker2").datetimepicker({
        defaultDate: false,
        autoclose: true
      });


      $('#datepicker1').on('change', function () {
        $("#datepicker1").prop( "readonly", true );
        var d = $('#datepicker1').datetimepicker('getValue');
        var dd = String(d.getDate()).padStart(2, '0');
        var mm = String(d.getMonth() + 1).padStart(2, '0'); //January is 0!
        var yyyy = d.getFullYear();
        var today = yyyy + '/' + mm + '/' + dd;
        if(d.getDate() == new Date().getDate()){
          $('#datepicker2').datetimepicker('setOptions', {
            minTime: 0,
            minDate: today,
          });
        }
        $('#datepicker2').datetimepicker('setOptions', {
          minDate: today,
        });
        // minTime: d.getTime() + (1*60*60*1000),
      });
      $('#datepicker2').on('change', function () {
        var d = $('#datepicker1').datetimepicker('getValue');
        var e = $('#datepicker2').datetimepicker('getValue');
        var dd = String(d.getDate()).padStart(2, '0');
        var mm = String(d.getMonth() + 1).padStart(2, '0'); //January is 0!
        var yyyy = d.getFullYear();
        var today = yyyy + '/' + mm + '/' + dd;
        $("#datepicker2").prop( "readonly", true );
        if(d.getDate() == e.getDate()){
          $('#datepicker2').datetimepicker('setOptions', {
            minTime: d.getTime() + (1*60*60*1000),
            minDate: today,
          });
        }else{
          $('#datepicker2').datetimepicker('setOptions', {
            minTime: "00:00 am",
          });
        }
      })
    });
</script>

app/views/service/laundry_service.html.erb
<%= render "layouts/partials/service_banner" %>
<section class="w3-service">
  <div class="container info-text">
    <p>
      Professional full shirt laundry service. You can choose to have your shirts hanging or folded. Folded shirts are individually packed with cellophane.
    </p>
    <span>
      Shirt Gold Services
    </span>
    <p>
      Your shirts will be brought back as near to new as we can get them. They will be packed on a wide board and be tissue’d. There really is no shirt service in London to match ours!
    </p>
</div>
</section>